version: '3'
services:
  blog-ui:
    build:
      context: ./blog-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./blog-ui:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - blog-api

  blog-api:
    build:
      context: ./blog-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./blog-api:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/blog
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
